version: '3.2'
services:
  mockServer:
    image: mockserver/mockserver:5.13.2
    command: -logLevel WARN -serverPort 1090
    ports:
      - 1090:1090
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: ./mockserver/
        target: /config
  jmeter-traffic-simulator:
    build:
      context: .
    depends_on:
      - mockServer
    ports:
      - "9001:9001"
    links:
      - mockServer:mockServer
    deploy:
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 1024m
