{
 "title": "JMeter Traffic Simulator",
 "tags": [ "provisioned" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jmeter_active_threads" }
   ]
  },
  {
   "title": "Configured Max Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jmeter_max_throughput_per_min" }
   ]
  },
  {
   "title": "Configured Min Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jmeter_min_throughput_per_min" }
   ]
  },
  {
   "title": "Calculated Percentage Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jmeter_percentage_reached" }
   ]
  },
  {
   "title": "Calculated Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jmeter_target_throughput_per_min"
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(jmeter_request_size_count{requestDirection=\"received\", requestName!=\"Populate custom prometheus metrics\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request Successful",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(jmeter_requests{requestName!=\"Populate custom prometheus metrics\",requestStatus=\"PASS\"}[2m])",
     "legendFormat": "{{requestName}}"
    }
   ]
  },
  {
   "title": "Request Failed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "increase(jmeter_requests{requestName!=\"Populate custom prometheus metrics\", requestStatus=\"FAIL\"}[2m])",
     "legendFormat": "{{requestName}}-{{responseCode}}"
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(jmeter_request_size_count{requestDirection=\"received\", requestName!=\"Populate custom prometheus metrics\"}[2m]))",
     "legendFormat": "CURRENT Throughput Sum"
    },
    {
     "expr": "increase(jmeter_request_size_count{requestDirection=\"received\", requestName=\"White noise - large\"}[2m])",
     "legendFormat": "{{requestName}}"
    },
    {
     "expr": "increase(jmeter_request_size_count{requestDirection=\"received\", requestName=\"White noise - medium\"}[2m])",
     "legendFormat": "{{requestName}}"
    },
    {
     "expr": "increase(jmeter_request_size_count{requestDirection=\"received\", requestName=\"White noise - small\"}[2m])",
     "legendFormat": "{{requestName}}"
    },
    { "expr": "jmeter_min_throughput_per_min", "legendFormat": "MIN Throughput" },
    { "expr": "jmeter_max_throughput_per_min", "legendFormat": "MAX Throughput" }
   ]
  },
  {
   "title": "Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(jmeter_requests[2m])) by (responseCode)",
     "legendFormat": "{{responseCode}}"
    },
    {
     "expr": "sum(increase(jmeter_requests{requestName!=\"Populate custom prometheus metrics\"}[2m])) by (responseCode, requestName)",
     "legendFormat": "{{responseCode}}-{{requestName}}"
    }
   ]
  },
  {
   "title": "Response Time By Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(jmeter_response_time{requestName!=\"Populate custom prometheus metrics\"}  > 0) by (quantile, requestName)",
     "legendFormat": "{{quantile}}-{{requestName}}"
    }
   ]
  }
 ]
}